server:
  port: 4885

spring:
  data:
    mongodb:
      database: cocoon
      username: cocoon
      password: cocoondev!@#$
      host: 192.168.0.200
      port: 27017

logging:
  level:
    org.springframework.data.mongodb: DEBUG

jwt:
  secret: mysecret
  expiration: 3600000
